### ISSUE TITLE
Tried to assault me

### ISSUE THREAD

**Issue by Dared-Daredevil** [LmaxplayG/KarpeBot#1]
My day was fine, perfect actually, i woke up with my 3 konkubines in my massive mansion, still having a headache from my most expensive vodka, when i went to my pool this Fis- NO, MONSTER CAME AT ME AND TRIED TO NOT ONLY ASSAULT, BUT I BELIEVE KILL ME ASWELL. AFTER I BEAT UP THAT LITTLE F*CK HE RAN AWAY WITH MY CREDIT CARD AND SPEND IT ALL ON VBUCKS, RUNESCAPE BONDS, AND BOOSTER COOKIES. ILL KILL HIM, EVEN IF ITS THE LAST THING ILL DO, RUN KARPE, RUN CAUSE IT WILL BE YOUR LAST ACTIVITY BEFORE TORTURE.

**Comment by LmaxplayG** [comment]
Not related to the bot. Please do not try this again. Its not funny.
